services:
  # FastAPI Backend (connects to cloud database)
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: budget_tracker_backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - DEBUG=true
      - HUGGINGFACE_API_KEY=${HUGGINGFACE_API_KEY}
      - GROQ_API_KEY=${GROQ_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./backend:/app
    command: uvicorn app.main_light:app --host 0.0.0.0 --port 8000 --reload

  # React Native Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: budget_tracker_frontend
    ports:
      - "19006:19006"  # Expo Dev Tools
      - "19000:19000"  # Expo Metro Bundler
      - "19001:19001"  # Expo Metro Bundler (iOS)
      - "19002:19002"  # Expo Metro Bundler (Android)
    environment:
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
      - API_BASE_URL=http://backend:8000
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    command: npm start

  # PostgreSQL Database
  db:
    image: postgres:15
    container_name: budget_tracker_db
    environment:
      POSTGRES_DB: budget_tracker
      POSTGRES_USER: budget_user
      POSTGRES_PASSWORD: budget_pass
    ports:
      - "5432:5432"
    volumes:
      - budget_data:/var/lib/postgresql/data

volumes:
  budget_data:
