services:
  # Minimal backend for testing
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: budget_tracker_backend_test
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - DEBUG=true
    volumes:
      - ./backend:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
